# Generated by Django 6.0.1 on 2026-02-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_nickname'),
        ('exam_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_exam_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='exam_dates.examdate'),
        ),
    ]
