# Generated by Django 6.0.1 on 2026-02-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_selected_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_math',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_verbal',
            field=models.IntegerField(default=600),
        ),
    ]
