# Generated by Django 6.0.1 on 2026-02-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_goal_math_profile_goal_verbal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university_icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
