# Generated by ChatGPT on 2026-02-13
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePractice",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("results_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        related_name="module_practices_created",
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModulePracticeAttempt",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("status", models.CharField(max_length=20, choices=[("in_progress", "In progress"), ("submitted", "Submitted")], default="in_progress")),
                ("answers", models.JSONField(default=dict)),
                ("module_scores", models.JSONField(default=dict)),
                ("score", models.FloatField(default=0)),
                ("correct", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True, blank=True)),
                (
                    "practice",
                    models.ForeignKey(
                        related_name="attempts",
                        to="module_practice.modulepractice",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        related_name="module_practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModulePracticeModule",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("subject", models.CharField(max_length=20, choices=[("verbal", "Verbal"), ("math", "Math")])),
                ("module_index", models.IntegerField()),
                ("question_ids", models.JSONField(default=list)),
                ("question_count", models.IntegerField(default=0)),
                ("time_limit_minutes", models.IntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practice",
                    models.ForeignKey(
                        related_name="modules",
                        to="module_practice.modulepractice",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
            options={
                "unique_together": {("practice", "subject", "module_index")},
            },
        ),
        migrations.CreateModel(
            name="ModulePracticeAccess",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(null=True, blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        related_name="module_practice_grants",
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        related_name="access_list",
                        to="module_practice.modulepractice",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        related_name="module_practice_access",
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
            options={
                "unique_together": {("practice", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="modulepracticemodule",
            index=models.Index(fields=["practice", "subject", "module_index"], name="module_prac_practice_60f8f8_idx"),
        ),
        migrations.AddIndex(
            model_name="modulepracticeaccess",
            index=models.Index(fields=["practice", "student"], name="module_prac_practice_5e6087_idx"),
        ),
        migrations.AddIndex(
            model_name="modulepracticeattempt",
            index=models.Index(fields=["practice", "student", "status"], name="module_prac_practice_28cbf3_idx"),
        ),
        migrations.AddIndex(
            model_name="modulepracticeattempt",
            index=models.Index(fields=["student", "started_at"], name="module_prac_student_0d58c5_idx"),
        ),
    ]
