# Generated by Django 6.0.1 on 2026-02-14 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePracticeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('verbal', 'Verbal'), ('math', 'Math')], max_length=20)),
                ('module_index', models.IntegerField()),
                ('topic_tag', models.CharField(max_length=200)),
                ('question_text', models.TextField()),
                ('passage', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(default=list)),
                ('is_open_ended', models.BooleanField(default=False)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='modulepracticeaccess',
            new_name='module_prac_practic_58d5a6_idx',
            old_name='module_prac_practice_5e6087_idx',
        ),
        migrations.RenameIndex(
            model_name='modulepracticeattempt',
            new_name='module_prac_practic_a03129_idx',
            old_name='module_prac_practice_28cbf3_idx',
        ),
        migrations.RenameIndex(
            model_name='modulepracticeattempt',
            new_name='module_prac_student_e5225b_idx',
            old_name='module_prac_student_0d58c5_idx',
        ),
        migrations.RenameIndex(
            model_name='modulepracticemodule',
            new_name='module_prac_practic_0aaf70_idx',
            old_name='module_prac_practice_60f8f8_idx',
        ),
        migrations.AddField(
            model_name='modulepracticequestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='module_practice.modulepracticemodule'),
        ),
        migrations.AddField(
            model_name='modulepracticequestion',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='module_practice.modulepractice'),
        ),
        migrations.AddIndex(
            model_name='modulepracticequestion',
            index=models.Index(fields=['practice', 'subject', 'module_index', 'order'], name='module_prac_practic_785810_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepracticequestion',
            index=models.Index(fields=['module', 'order'], name='module_prac_module__48ba75_idx'),
        ),
    ]
