# Generated by Codex on 2026-02-15

from django.db import migrations, models


def set_required_counts(apps, schema_editor):
    ModulePracticeModule = apps.get_model("module_practice", "ModulePracticeModule")
    for module in ModulePracticeModule.objects.all():
        if module.required_count and module.required_count > 0:
            continue
        module.required_count = 22 if module.subject == "math" else 27
        module.save(update_fields=["required_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("module_practice", "0002_modulepracticequestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepracticemodule",
            name="required_count",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_required_counts, migrations.RunPython.noop),
    ]

