# Generated by hand on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_practice", "0002_modulepracticequestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepracticequestion",
            name="difficulty",
            field=models.CharField(max_length=10, blank=True, null=True),
        ),
    ]
