# Generated by Django 6.0.1 on 2026-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_practice', '0003_modulepracticequestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepractice',
            name='exam_type',
            field=models.CharField(choices=[('sat', 'SAT'), ('act', 'ACT')], default='sat', max_length=10),
        ),
    ]
