# Generated by Django 6.0.1 on 2026-02-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_practice', '0003_modulepracticemodule_required_count'),
        ('module_practice', '0004_modulepractice_exam_type'),
    ]

    operations = [
    ]
