# Generated by Django 6.0.1 on 2026-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_practice', '0005_merge_20260215_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepractice',
            name='allow_retakes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modulepractice',
            name='shuffle_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulepractice',
            name='shuffle_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modulepracticeattempt',
            name='choice_order',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='modulepracticeattempt',
            name='question_order',
            field=models.JSONField(default=dict),
        ),
    ]
