# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_practice", "0006_modulepractice_allow_retakes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepractice",
            name="retake_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
