# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_practice", "0007_modulepractice_retake_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepracticeaccess",
            name="attempt_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
