# Generated by Codex on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("module_practice", "0008_modulepracticeaccess_attempt_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepractice",
            name="allowed_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="module_practices_allowed",
                to="courses.course",
            ),
        ),
    ]
