# Generated by Django 6.0.1 on 2026-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='selected_label',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
