# Generated by Codex on 2026-02-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockExam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("verbal_question_count", models.IntegerField(default=0)),
                ("math_question_count", models.IntegerField(default=0)),
                ("total_time_minutes", models.IntegerField(default=120)),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("shuffle_choices", models.BooleanField(default=False)),
                ("allow_retakes", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("results_published", models.BooleanField(default=False)),
                ("question_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_exams_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockExamAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("in_progress", "In progress"), ("submitted", "Submitted")], default="in_progress", max_length=20)),
                ("answers", models.JSONField(default=dict)),
                ("question_order", models.JSONField(default=list)),
                ("choice_order", models.JSONField(default=dict)),
                ("score_verbal", models.IntegerField(default=0)),
                ("score_math", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("analytics", models.JSONField(default=dict)),
                ("time_spent", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mock_exam",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="mock_exams.mockexam"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_exam_attempts", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mockexamattempt",
            index=models.Index(fields=["mock_exam", "student", "status"], name="mock_exams_mock_ex_74a79e_idx"),
        ),
        migrations.AddIndex(
            model_name="mockexamattempt",
            index=models.Index(fields=["student", "started_at"], name="mock_exams_student_7c4b7f_idx"),
        ),
    ]

