# Generated by Django 6.0.1 on 2026-02-15 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mockexamattempt',
            new_name='mock_exams__mock_ex_f6ae2e_idx',
            old_name='mock_exams_mock_ex_74a79e_idx',
        ),
        migrations.RenameIndex(
            model_name='mockexamattempt',
            new_name='mock_exams__student_6e604e_idx',
            old_name='mock_exams_student_7c4b7f_idx',
        ),
        migrations.AddField(
            model_name='mockexam',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, related_name='mock_exams_allowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
