# Generated by Codex on 2026-02-16

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mock_exams", "0003_mockexam_retake_limit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockExamAccess",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempt_limit", models.IntegerField(blank=True, null=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mock_exam",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="access_list", to="mock_exams.mockexam"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="mock_exam_access", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="mock_exam_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("mock_exam", "student")},
                "indexes": [models.Index(fields=["mock_exam", "student"], name="mock_exams_mock_exam_id_student_id_idx")],
            },
        ),
    ]
