# Generated by Codex on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("mock_exams", "0006_mockexam_question_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexam",
            name="allowed_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="mock_exams_allowed",
                to="courses.course",
            ),
        ),
    ]
