# Generated by Django 6.0.1 on 2026-03-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_exams', '0007_mockexam_allowed_courses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mockexamaccess',
            new_name='mock_exams__mock_ex_4f33d4_idx',
            old_name='mock_exams_mock_exam_id_student_id_idx',
        ),
    ]
