# Generated by Django 5.0 on 2026-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
