# Generated by Django 6.0.1 on 2026-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursenode_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenode',
            name='kind',
            field=models.CharField(choices=[('folder', 'folder'), ('file', 'file'), ('assignment', 'assignment'), ('quiz', 'quiz')], max_length=20),
        ),
    ]
