# Generated by Django 6.0.1 on 2026-02-12 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_add_is_open_ended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('verbal', 'Verbal'), ('math', 'Math')], max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(max_length=200)),
                ('best_score', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject'], name='question_ba_user_id_371271_idx'), models.Index(fields=['subject', 'topic'], name='question_ba_subject_60c247_idx')],
                'unique_together': {('user', 'subject', 'topic', 'subtopic')},
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('verbal', 'Verbal'), ('math', 'Math')], max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('best_score', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject'], name='question_ba_user_id_579cb0_idx'), models.Index(fields=['subject', 'topic'], name='question_ba_subject_07ed22_idx')],
                'unique_together': {('user', 'subject', 'topic')},
            },
        ),
    ]
