# Generated by Django 5.0 on 2026-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_submissions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
