# Generated by Django 5.0 on 2026-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_offlineunit_offlinegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineunit',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
