from django.urls import path
from .views import (
    ModulePracticeListView,
    ModulePracticeCreateView,
    ModulePracticeUpdateView,
    ModulePracticeDeleteView,
    ModulePracticeModuleSetView,
    ModulePracticeQuestionListView,
    ModulePracticeQuestionCreateView,
    ModulePracticeQuestionUpdateView,
    ModulePracticeQuestionDeleteView,
    ModulePracticeQuestionImportView,
    ModulePracticeQuestionDetailView,
    ModulePracticeAccessGrantView,
    ModulePracticeAccessRevokeView,
    ModulePracticeStudentSearchView,
    ModulePracticeStudentLookupView,
    ModulePracticeAccessSetView,
    ModulePracticeStartView,
    ModulePracticeSubmitView,
)

urlpatterns = [
    path("module-practice/list/", ModulePracticeListView.as_view(), name="module_practice_list"),
    path("module-practice/create/", ModulePracticeCreateView.as_view(), name="module_practice_create"),
    path("module-practice/update/", ModulePracticeUpdateView.as_view(), name="module_practice_update"),
    path("module-practice/delete/", ModulePracticeDeleteView.as_view(), name="module_practice_delete"),
    path("module-practice/modules/set/", ModulePracticeModuleSetView.as_view(), name="module_practice_module_set"),
    path("module-practice/questions/list/", ModulePracticeQuestionListView.as_view(), name="module_practice_questions_list"),
    path("module-practice/questions/create/", ModulePracticeQuestionCreateView.as_view(), name="module_practice_questions_create"),
    path("module-practice/questions/update/", ModulePracticeQuestionUpdateView.as_view(), name="module_practice_questions_update"),
    path("module-practice/questions/delete/", ModulePracticeQuestionDeleteView.as_view(), name="module_practice_questions_delete"),
    path("module-practice/questions/import/", ModulePracticeQuestionImportView.as_view(), name="module_practice_questions_import"),
    path("module-practice/questions/<uuid:question_id>/", ModulePracticeQuestionDetailView.as_view(), name="module_practice_questions_detail"),
    path("module-practice/access/grant/", ModulePracticeAccessGrantView.as_view(), name="module_practice_access_grant"),
    path("module-practice/access/revoke/", ModulePracticeAccessRevokeView.as_view(), name="module_practice_access_revoke"),
    path("module-practice/students/search/", ModulePracticeStudentSearchView.as_view(), name="module_practice_students_search"),
    path("module-practice/students/lookup/", ModulePracticeStudentLookupView.as_view(), name="module_practice_students_lookup"),
    path("module-practice/access/set/", ModulePracticeAccessSetView.as_view(), name="module_practice_access_set"),
    path("module-practice/start/", ModulePracticeStartView.as_view(), name="module_practice_start"),
    path("module-practice/submit/", ModulePracticeSubmitView.as_view(), name="module_practice_submit"),
]
